// EXAMPLE GENERATED COMPONENT - DO NOT EDIT MANUALLY
// Generated by Rive MCP Generator - Phase 1 Features
// Generated: 2025-11-09

import React, { useEffect, useRef, useState, useImperativeHandle, forwardRef } from "react";
import { useRive, useStateMachineInput, Layout, Fit, Alignment } from "@rive-app/react-canvas";

/**
 * Imperative handle for controlling LoadingSpinner playback
 */
export interface LoadingSpinnerHandle {
  /** Start or resume animation playback */
  play: () => void;
  /** Pause animation playback */
  pause: () => void;
  /** Stop animation playback and reset to beginning */
  stop: () => void;
  /** Reset animation to initial state */
  reset: () => void;
  /** Scrub to a specific time in the animation */
  scrub: (time: number) => void;
  /** Check if animation is currently playing */
  isPlaying: () => boolean;
  /** Get current playback time */
  getTime: () => number;
}

/**
 * Props for LoadingSpinner component
 */
export interface LoadingSpinnerProps {
  /**
   * State machine input: isLoading
   * @default true
   */
  isLoading?: boolean;
  /**
   * State machine input: progress
   * @default 0
   */
  progress?: number;
  /**
   * State machine input: speed
   * @default 1.0
   */
  speed?: number;
  /**
   * Event handler for: LoadingStarted
   * Fired when loading begins
   */
  onLoadingStarted?: (payload: any) => void;
  /**
   * Event handler for: LoadingComplete
   * Fired when loading completes
   */
  onLoadingComplete?: (payload: any) => void;

  /** Layout & Rendering */

  /**
   * How the animation should fit within its container
   * @default "contain"
   */
  fit?: "cover" | "contain" | "fill" | "fitWidth" | "fitHeight" | "none" | "scaleDown";

  /**
   * Alignment of the animation within its container
   * @default "center"
   */
  alignment?: "center" | "topLeft" | "topCenter" | "topRight" | "centerLeft" | "centerRight" | "bottomLeft" | "bottomCenter" | "bottomRight";

  /**
   * Automatically resize the animation when the window resizes
   * @default false
   */
  autoResize?: boolean;

  /** Lifecycle Callbacks */

  /**
   * Called when loading state changes
   */
  onLoadingStateChange?: (loading: boolean) => void;

  /**
   * Called when an error occurs during loading
   */
  onError?: (error: Error) => void;

  /**
   * Called when the animation has finished loading
   */
  onLoadComplete?: () => void;
}

/**
 * LoadingSpinner - A Rive-powered component
 *
 * This component is automatically generated and provides type-safe props
 * for all state machine inputs and events.
 *
 * Features:
 * - Layout controls (fit, alignment, autoResize)
 * - Playback controls via ref (play, pause, stop, reset, scrub)
 * - Single state machine
 * - Error handling and loading states
 * - Lifecycle callbacks
 *
 * @component
 */
export const LoadingSpinner = forwardRef<LoadingSpinnerHandle, LoadingSpinnerProps>(({
  isLoading,
  progress,
  speed,
  onLoadingStarted,
  onLoadingComplete,
  fit,
  alignment,
  autoResize,
  onLoadingStateChange,
  onError,
  onLoadComplete
}, ref) => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Determine which state machine to use
  const activeStateMachine = "LoadingStateMachine";

  const { rive, RiveComponent } = useRive({
    src: "/animations/loading-spinner.riv",
    stateMachines: [activeStateMachine],
    autoplay: true,
    layout: new Layout({
      fit: fit ? Fit[fit] : Fit.Contain,
      alignment: alignment ? Alignment[alignment] : Alignment.Center,
    }),
    onLoad: () => {
      setLoading(false);
      onLoadComplete?.();
    },
    onLoadError: (err: any) => {
      const errorObj = err instanceof Error ? err : new Error(String(err));
      setError(errorObj);
      onError?.(errorObj);
    }
  });

  const isLoadingInput = useStateMachineInput(rive, "LoadingStateMachine", "isLoading");
  const progressInput = useStateMachineInput(rive, "LoadingStateMachine", "progress");
  const speedInput = useStateMachineInput(rive, "LoadingStateMachine", "speed");

  useEffect(() => {
    if (isLoadingInput && isLoading !== undefined) {
      isLoadingInput.value = isLoading;
    }
  }, [isLoading, isLoadingInput]);

  useEffect(() => {
    if (progressInput && progress !== undefined) {
      progressInput.value = progress;
    }
  }, [progress, progressInput]);

  useEffect(() => {
    if (speedInput && speed !== undefined) {
      speedInput.value = speed;
    }
  }, [speed, speedInput]);

  useEffect(() => {
    if (!rive || !onLoadingStarted) return;
    const handler = (riveEvent: any) => {
      if (riveEvent.data?.name === "LoadingStarted") {
        onLoadingStarted(riveEvent.data);
      }
    };
    rive.on("event", handler);
    return () => {
      rive.off("event", handler);
    };
  }, [rive, onLoadingStarted]);

  useEffect(() => {
    if (!rive || !onLoadingComplete) return;
    const handler = (riveEvent: any) => {
      if (riveEvent.data?.name === "LoadingComplete") {
        onLoadingComplete(riveEvent.data);
      }
    };
    rive.on("event", handler);
    return () => {
      rive.off("event", handler);
    };
  }, [rive, onLoadingComplete]);

  // Expose playback controls via ref
  useImperativeHandle(ref, () => ({
    play: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.play() or similar
      console.warn("LoadingSpinner.play() - Awaiting Rive playback API details from Agent 3");
    },
    pause: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.pause() or similar
      console.warn("LoadingSpinner.pause() - Awaiting Rive playback API details from Agent 3");
    },
    stop: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.stop() or rive?.reset() and pause
      console.warn("LoadingSpinner.stop() - Awaiting Rive playback API details from Agent 3");
    },
    reset: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.reset() or similar
      console.warn("LoadingSpinner.reset() - Awaiting Rive playback API details from Agent 3");
    },
    scrub: (time: number) => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.scrub(time) or rive.currentTime = time
      console.warn("LoadingSpinner.scrub(time) - Awaiting Rive playback API details from Agent 3");
    },
    isPlaying: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.isPlaying or similar
      console.warn("LoadingSpinner.isPlaying() - Awaiting Rive playback API details from Agent 3");
      return false;
    },
    getTime: () => {
      // TODO: Implement based on Agent 3's Rive playback API research
      // Expected: rive?.currentTime or similar
      console.warn("LoadingSpinner.getTime() - Awaiting Rive playback API details from Agent 3");
      return 0;
    }
  }), [rive]);

  // Handle loading state changes
  useEffect(() => {
    onLoadingStateChange?.(loading);
  }, [loading, onLoadingStateChange]);

  // Handle window resize if autoResize is enabled
  useEffect(() => {
    if (!autoResize || !rive) return;

    const handleResize = () => {
      // TODO: Implement based on Agent 2's Rive resize API research
      // Expected: rive.resizeDrawingSurfaceToCanvas() or similar
      console.warn("LoadingSpinner resize - Awaiting Rive resize API details from Agent 2");
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, [autoResize, rive]);

  // Error state rendering
  if (error) {
    return (
      <div className="loadingspinner-error" style={{ padding: "1rem", color: "#dc2626" }}>
        Error loading animation: {error.message}
      </div>
    );
  }

  // Loading state rendering
  if (loading) {
    return (
      <div className="loadingspinner-loading" style={{ padding: "1rem", color: "#6b7280" }}>
        Loading animation...
      </div>
    );
  }

  return (
    <div ref={containerRef} className="loadingspinner-wrapper">
      <RiveComponent />
    </div>
  );
});

LoadingSpinner.displayName = "LoadingSpinner";
